todos/config/routes.rb
Todos::Application.routes.draw do
  root to: 'high_voltage/pages#show', id: 'homepage'
  resources :todos, only: [:index, :new, :create] do
    resource :completion, only: [:create]
  end

  resource :session, only: [:new, :create]
end

todos/app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :owner_email, presence: true

  def completed?
    completed_at?
  end
end

todos/app/models/user.rb
class User
  def initialize(email)
    @email = email
  end

  def todos
    Todo.where(owner_email: @email)
  end
end

todos/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery with: :exception

  def sign_in_as(email)
    session[:current_email] = email
  end

  def current_user
    User.new(session[:current_email])
  end

end

todos/app/controllers/completions_controller.rb
class CompletionsController < ApplicationController
  def create
    todo = current_user.todos.find(params[:todo_id])
    todo.touch :completed_at
    redirect_to todos_path
  end
end

todos/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    sign_in_as(params[:session][:email]) 
    redirect_to todos_path
  end
end

todos/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = current_user.todos 
  end

  def new
    @todo = Todo.new
  end

  def create
    current_user.todos.create params[:todo].permit(:name)
    redirect_to todos_path
  end

end

todos/app/helpers/application_helper.rb
module ApplicationHelper
end

todos/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todos</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

todos/app/views/pages/homepage.html.erb
<h1>Welcome to Todos!</h1>
<p data-role="description">This is an awesome application for managging todos!</p>

<%= link_to 'Sign in', new_session_path %>

todos/app/views/todos/index.html.erb
<%= link_to 'Add new todo', new_todo_path %>

<ul class="todos">
  <% @todos.each do |todo|%>
    <li class="<%= 'completed' if todo.completed?  %>">
      <%= todo.name %>
      <%= link_to 'Mark complete', todo_completion_path(todo), method: :post %>
    </li>
  <% end %>
</ul>

todos/app/views/todos/new.html.erb
<%= form_for @todo do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.submit "Submit" %>
 <% end %>